In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

from sklearn.cluster import KMeans

#import decisiontreeclassifier
from sklearn import tree
from sklearn.tree import DecisionTreeClassifier
#import logisticregression classifier
from sklearn.linear_model import LogisticRegression
import statsmodels.api as sm
#import knn classifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier

#for validating your classification model
from sklearn.cross_validation import train_test_split
from sklearn.cross_validation import cross_val_score
from sklearn import metrics
from sklearn.metrics import roc_curve, auc


C:\ProgramData\Anaconda2\lib\site-packages\statsmodels\compat\pandas.py:56: FutureWarning: The pandas.core.datetools module is deprecated and will be removed in a future version. Please use the pandas.tseries module instead.
  from pandas.core import datetools
C:\ProgramData\Anaconda2\lib\site-packages\sklearn\cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


In [2]:
import glob, os 
import pandas as pd
path =r'...Layers'
all_files = glob.glob(os.path.join(path, "*.csv")) 

In [3]:
j=1
df_f=pd.DataFrame()
for file_ in all_files:
    df=pd.read_csv(file_)
    
    from scipy.spatial.distance import cdist 
    K = range(1, 10) 
    meandistortions = []
    for k in K: 
        kmeans = KMeans(n_clusters=k) 
        kmeans.fit(df) 
        meandistortions.append(sum(np.min(cdist(df, kmeans.cluster_centers_, 'euclidean'), axis=1)) / df.shape[0]) 
    maxx=0.0
    maxx_indx=0.0
    dif=0.0
    dif_indx=0.0
    for i in range(len(meandistortions)-1):
        dif=meandistortions[i]-meandistortions[i+1]
        dif_indx=i+2
        if dif>maxx:
            maxx=dif
            maxx_indx=dif_indx
    
    k_means = KMeans(init='k-means++', n_clusters=maxx_indx, random_state=0)
    k_means.fit(df)
    df1 = pd.DataFrame(k_means.labels_, columns = [str(j)+'_cluster'])
    df_f = pd.concat([df_f, df1], axis=1)
    j=j+1

In [4]:
df_f.describe()

1_cluster    2_cluster    3_cluster    4_cluster    5_cluster  \
count  1000.000000  1000.000000  1000.000000  1000.000000  1000.000000   
mean      0.518000     0.509000     0.494000     0.504000     0.492000   
std       0.499926     0.500169     0.500214     0.500234     0.500186   
min       0.000000     0.000000     0.000000     0.000000     0.000000   
25%       0.000000     0.000000     0.000000     0.000000     0.000000   
50%       1.000000     1.000000     0.000000     1.000000     0.000000   
75%       1.000000     1.000000     1.000000     1.000000     1.000000   
max       1.000000     1.000000     1.000000     1.000000     1.000000   

         6_cluster    7_cluster    8_cluster    9_cluster   10_cluster  \
count  1000.000000  1000.000000  1000.000000  1000.000000  1000.000000   
mean      0.529000     0.522000     0.513000     0.487000     0.516000   
std       0.499408     0.499766     0.500081     0.500081     0.499994   
min       0.000000     0.000000     0.000000     0.000000     0.000000   
25%       0.000000     0.000000     0.000000     0.000000     0.000000   
50%       1.000000     1.000000     1.000000     0.000000     1.000000   
75%       1.000000     1.000000     1.000000     1.000000     1.000000   
max       1.000000     1.000000     1.000000     1.000000     1.000000   

          ...        91_cluster   92_cluster   93_cluster   94_cluster  \
count     ...       1000.000000  1000.000000  1000.000000  1000.000000   
mean      ...          0.504000     0.525000     0.503000     0.486000   
std       ...          0.500234     0.499624     0.500241     0.500054   
min       ...          0.000000     0.000000     0.000000     0.000000   
25%       ...          0.000000     0.000000     0.000000     0.000000   
50%       ...          1.000000     1.000000     1.000000     0.000000   
75%       ...          1.000000     1.000000     1.000000     1.000000   
max       ...          1.000000     1.000000     1.000000     1.000000   

        95_cluster   96_cluster   97_cluster   98_cluster  99_cluster  \
count  1000.000000  1000.000000  1000.000000  1000.000000  1000.00000   
mean      0.513000     0.505000     0.506000     0.478000     0.51000   
std       0.500081     0.500225     0.500214     0.499766     0.50015   
min       0.000000     0.000000     0.000000     0.000000     0.00000   
25%       0.000000     0.000000     0.000000     0.000000     0.00000   
50%       1.000000     1.000000     1.000000     0.000000     1.00000   
75%       1.000000     1.000000     1.000000     1.000000     1.00000   
max       1.000000     1.000000     1.000000     1.000000     1.00000   

       100_cluster  
count  1000.000000  
mean      0.517000  
std       0.499961  
min       0.000000  
25%       0.000000  
50%       1.000000  
75%       1.000000  
max       1.000000  

[8 rows x 100 columns]

In [5]:
df_f

1_cluster  2_cluster  3_cluster  4_cluster  5_cluster  6_cluster  \
0            1          1          0          0          1          1   
1            1          1          0          1          0          1   
2            1          1          0          0          0          0   
3            0          0          0          1          0          1   
4            0          1          1          0          1          0   
5            1          1          1          0          1          0   
6            1          1          0          0          1          0   
7            1          1          0          1          0          1   
8            1          0          0          1          0          1   
9            1          1          1          1          0          0   
10           0          1          0          0          0          0   
11           1          1          0          1          1          1   
12           0          0          0          1          0          0   
13           1          1          0          0          1          1   
14           1          0          1          1          0          1   
15           1          1          0          0          0          0   
16           1          1          0          1          0          0   
17           0          1          1          1          0          1   
18           0          1          0          1          0          1   
19           1          0          0          0          0          0   
20           0          0          1          1          0          1   
21           0          1          1          1          1          1   
22           0          0          0          1          0          1   
23           0          0          0          0          1          1   
24           0          0          1          0          1          1   
25           0          0          0          1          1          1   
26           1          0          1          1          1          1   
27           0          1          1          0          0          0   
28           1          0          1          1          0          1   
29           0          0          1          1          0          0   
..         ...        ...        ...        ...        ...        ...   
970          1          0          1          0          0          0   
971          0          0          0          0          1          0   
972          0          1          0          1          0          0   
973          0          1          1          0          1          1   
974          0          1          0          0          1          0   
975          0          1          0          0          0          1   
976          1          1          0          0          1          0   
977          0          0          0          1          1          1   
978          0          1          0          1          0          1   
979          0          0          1          1          1          1   
980          0          0          1          1          1          1   
981          1          0          0          0          1          1   
982          0          0          0          1          1          1   
983          1          0          1          0          1          1   
984          0          1          1          1          0          0   
985          0          1          1          1          0          1   
986          0          0          0          1          0          0   
987          1          1          0          1          0          0   
988          1          1          1          0          0          0   
989          1          1          1          0          1          0   
990          0          0          1          1          1          1   
991          1          1          1          0          1          1   
992          0          1          0          0          0     

In [6]:
df_y=pd.read_csv('...y.csv')

In [7]:
df_y['y'].value_counts()

0    724
1    276
Name: y, dtype: int64

In [8]:
y = df_y['y']
X = df_f

In [9]:
# evaluate the model by splitting into train (90%) and test sets (10%)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.1, random_state=0)
clf = RandomForestClassifier(n_estimators=20)
clf=clf.fit(X_train, y_train)

In [10]:
print metrics.accuracy_score(y_test, clf.predict(X_test))

print metrics.confusion_matrix(y_test, clf.predict(X_test))

0.77
[[70  4]
 [19  7]]


In [11]:
l_imp=[]
Layer_importance=(clf.feature_importances_ )
for i in range(len(Layer_importance)):
    l_imp.append([i+1,Layer_importance[i]])
#print Layer_importance, index(Layer_importance)
df_l_imp=pd.DataFrame(l_imp)
df_l_imp.columns = ['layer', 'importance']
df_l_imp.sort_values('importance', ascending=False)

layer  importance
96     97    0.038825
10     11    0.034931
12     13    0.034576
56     57    0.022735
51     52    0.022423
28     29    0.014993
47     48    0.014898
44     45    0.014805
88     89    0.014470
35     36    0.013817
39     40    0.013403
30     31    0.013172
22     23    0.012873
63     64    0.012570
64     65    0.012539
75     76    0.012496
92     93    0.012354
3       4    0.011804
1       2    0.011698
53     54    0.011601
4       5    0.011456
69     70    0.010795
41     42    0.010743
85     86    0.010690
93     94    0.010681
94     95    0.010612
52     53    0.010469
71     72    0.010207
77     78    0.010108
82     83    0.009984
..    ...         ...
74     75    0.007456
38     39    0.007435
61     62    0.007402
81     82    0.007354
40     41    0.007319
91     92    0.007298
58     59    0.007223
46     47    0.007222
24     25    0.007220
29     30    0.007193
37     38    0.007170
70     71    0.007090
16     17    0.006953
36     37    0.006855
54     55    0.006728
43     44    0.006639
8       9    0.006606
65     66    0.006544
13     14    0.006540
18     19    0.006322
42     43    0.006084
34     35    0.006057
11     12    0.006034
86     87    0.005999
60     61    0.005800
21     22    0.005736
5       6    0.005580
57     58    0.005485
23     24    0.005140
87     88    0.004359

[100 rows x 2 columns]

In [12]:
df_l_imp.head(10)

layer  importance
0      1    0.008807
1      2    0.011698
2      3    0.007715
3      4    0.011804
4      5    0.011456
5      6    0.005580
6      7    0.009622
7      8    0.008179
8      9    0.006606
9     10    0.007525

In [13]:
df_l_imp

layer  importance
0       1    0.008807
1       2    0.011698
2       3    0.007715
3       4    0.011804
4       5    0.011456
5       6    0.005580
6       7    0.009622
7       8    0.008179
8       9    0.006606
9      10    0.007525
10     11    0.034931
11     12    0.006034
12     13    0.034576
13     14    0.006540
14     15    0.008617
15     16    0.008986
16     17    0.006953
17     18    0.009131
18     19    0.006322
19     20    0.007466
20     21    0.009397
21     22    0.005736
22     23    0.012873
23     24    0.005140
24     25    0.007220
25     26    0.009697
26     27    0.009608
27     28    0.008301
28     29    0.014993
29     30    0.007193
..    ...         ...
70     71    0.007090
71     72    0.010207
72     73    0.009617
73     74    0.008318
74     75    0.007456
75     76    0.012496
76     77    0.008171
77     78    0.010108
78     79    0.009054
79     80    0.008115
80     81    0.009557
81     82    0.007354
82     83    0.009984
83     84    0.007513
84     85    0.007632
85     86    0.010690
86     87    0.005999
87     88    0.004359
88     89    0.014470
89     90    0.008196
90     91    0.009260
91     92    0.007298
92     93    0.012354
93     94    0.010681
94     95    0.010612
95     96    0.007980
96     97    0.038825
97     98    0.009706
98     99    0.008287
99    100    0.009289

[100 rows x 2 columns]

In [14]:
df_l_imp[df_l_imp['importance']>0.013].sort_values('layer')

layer  importance
10     11    0.034931
12     13    0.034576
28     29    0.014993
30     31    0.013172
35     36    0.013817
39     40    0.013403
44     45    0.014805
47     48    0.014898
51     52    0.022423
56     57    0.022735
88     89    0.014470
96     97    0.038825

In [15]:
len(df_l_imp[df_l_imp['importance']>0.013])

12

In [16]:
X2=X[['1_cluster','2_cluster','3_cluster','4_cluster','5_cluster','6_cluster','7_cluster','8_cluster','9_cluster','10_cluster','11_cluster']]
X3=X[['1_cluster','2_cluster','3_cluster','4_cluster','5_cluster','6_cluster','7_cluster','8_cluster','9_cluster','10_cluster','11_cluster','12_cluster','13_cluster']]

In [19]:
X_train, X_test, y_train, y_test = train_test_split(X2, y, test_size=0.1, random_state=0)
clf = RandomForestClassifier(n_estimators=20)
clf=clf.fit(X_train, y_train)
print metrics.accuracy_score(y_test, clf.predict(X_test))

print metrics.confusion_matrix(y_test, clf.predict(X_test))

0.75
[[64 10]
 [15 11]]


In [22]:
X_train, X_test, y_train, y_test = train_test_split(X3, y, test_size=0.1, random_state=0)
clf = RandomForestClassifier(n_estimators=20)
clf=clf.fit(X_train, y_train)
print metrics.accuracy_score(y_test, clf.predict(X_test))

print metrics.confusion_matrix(y_test, clf.predict(X_test))

0.79
[[69  5]
 [16 10]]
